### ISSUE TITLE
Harvesting section

### ISSUE THREAD

**Issue by roblokers** [soilwise-he/SoilWise-documentation#14]
Some suggestions for improvement of the section

- [ ] For the 2nd approach can we add also RDF writer and triple store to the diagram?
- [ ] Can the technology options be linked to the approaches

**Comment by DajanaSnopkova** [comment]
Please, now it is time to work on this (deadline mid-september). We will deliver updated version of Technical documentation together with the first prototype.

In the architecture diagram we currently have Triple store and function of Harvester called transformation to triple store. Should I rename it to RDF writer?

**Comment by roblokers** [comment]
With the knowledge of today, I would probably add an independent component RDF writer between the RDBMS and the triple store. Basically we choose to store the outputs of several components to PostGreSQL (harvester, interlinker, validation) and only push the results to the triple store at intervals. To be decided / updated in consultation with Paul
