### ISSUE TITLE
Pycsw section

### ISSUE THREAD

**Issue by roblokers** [soilwise-he/SoilWise-documentation#17]
This is a bit of a weird chapter compared to others. It would be more logical if it was just named catalogue, with pycsw as a (the only, preferred?) candidate, mentioning e.g. also GeoNetwork and the why of the choice for pycsw

A bit more text in this section would help, e.g. what does M, S, W mean under functionality...

**Comment by DajanaSnopkova** [comment]
I agree the chapter is different compared to others... I went with the title pycsw because in the Architecture diagram, the SWR Catalog covers many more components and I thought it could be confusing...

**Comment by DajanaSnopkova** [comment]
Luis did some revisions, provided general intro and section on GeoNetwork.
