### ISSUE TITLE
Improve the alignment of the descriptions of various knowledge related components

### ISSUE THREAD

**Issue by robknapen** [soilwise-he/SoilWise-documentation#32]
Some of the descriptions appear to be a bit detached at the moment, e.g. between storage (triple store) and LLM (to be renamed to natural language querying), and other ontology and ML related text. Views on these components can be further aligned I think, now that we have progressed a little.

**Comment by DajanaSnopkova** [comment]
Please, now it is time to work on this (deadline mid-september). We will deliver updated version of Technical documentation together with the first prototype.
