### ISSUE TITLE
Metadata validation - Technical documentation update

### ISSUE THREAD

**Issue by DajanaSnopkova** [soilwise-he/SoilWise-documentation#37]
Please revise chapter. Divide it to **Functionality** (description of what is delivered in 1st prototype, should correspond with the Excel) and **Future work** (everything else). Also **Technology options** should be revised and only what we are using in the first prototype should remain here.

**Comment by DajanaSnopkova** [comment]
Added chapter with metadata profiles used for validation.

**Comment by DajanaSnopkova** [comment]
Link liveliness assessment component was moved under metadata validation, please @vgole001 can you provide it's description?

**Comment by vgole001** [comment]
@DajanaSnopkova I can provide the description of the **Link liveliness assessment** component
Should I add it directly in the [metadata.md](https://github.com/soilwise-he/SoilWise-documentation/blob/main/tech/docs/technical_components/metadata_validation.md) file?

**Comment by DajanaSnopkova** [comment]
Yes, that works for me :)

**Comment by vgole001** [comment]
I've pushed the changes to this [commit](https://github.com/soilwise-he/SoilWise-documentation/commit/a7c612172c5084207afe05f66329edcebc4bc56f)
Let me know if additional changes are needed

**Comment by DajanaSnopkova** [comment]
Thanks a lot! I only did some small renaming and added links... You can check my review here: [commit](https://github.com/soilwise-he/SoilWise-documentation/commit/672eb0ba020574066e25d4db344ca6ad1334c06f)

**Comment by vgole001** [comment]
It looks good to me. 
As an improvement the Swagger keyword on [Technology](https://github.com/soilwise-he/SoilWise-documentation/blob/main/tech/docs/technical_components/metadata_validation.md#technology) section could also be a reference [Swagger](https://swagger.io/docs/specification/2-0/what-is-swagger/)
