### ISSUE TITLE
NLQ - Technical Documentation update

### ISSUE THREAD

**Issue by DajanaSnopkova** [soilwise-he/SoilWise-documentation#49]
This component will (probably) not be a part of the first prototype. However Foreseen functionality and technology can be described (should be aligned with the [Excel](https://ilvo.sharepoint.com/:x:/r/sites/HESoilWiseProject/Gedeelde%20documenten/WP7/T7.2%20Technical%20and%20Scientific%20Management,%20M1-M48%20(MU,%20EV%20ILVO,%20ISRIC,%20WR,%20BIOS,%20WE)/evaluation%20technical%20development%20first%20prototype.xlsx?d=w25975383f9c44f3098d8e6d961c55316&csf=1&web=1&e=E6vOmo)).

**Comment by robknapen** [comment]
I wrote an initial version as a proposal. Please review it @roblokers and @pvgenuchten, and provide feedback (if needed).
