### ISSUE TITLE
Internal review D2.1 Technical documentation

### ISSUE THREAD

**Issue by blitzfrayret** [soilwise-he/SoilWise-documentation#54]
https://soilwise-he.github.io/SoilWise-documentation/

- [x] Merging the Table of contents (« Terminology » and « release notes ») with « Technical components », « APIs », « infrastructure », « glossary » and « Printable version » ?

https://soilwise-he.github.io/SoilWise-documentation/technical_components/technical_components/

- [x] 1st sentence : I would suggest to remove ‘store data’ to prevent from misunderstanding that Soilwise does not intent to store data
- [ ] Figure : is it possible to set the view box of the figure directly on the architecture schema of  SWR ? 

https://soilwise-he.github.io/SoilWise-documentation/technical_components/ingestion/
- [x] ‘Disucssion ‘ to be corrected
- [x] ‘Datasets are to be primarily imported ‘ : is it the metadata of the dataset ? because the only word ‘dataset’ can be refered to the entire dataset, including the data.
- [x] ‘deliverables from which projects to be included’ Don’t understand
- [x] ‘Metadata augmentation’ does not appear in the harvester functionalities bullet points. Should it be removed from this page ?

https://soilwise-he.github.io/SoilWise-documentation/technical_components/metadata_augmentation/
- [x]  Write « foreseen functionalities  » at the same level of title than « Automatic metadata generation » and « Spatial scope analyser »

https://soilwise-he.github.io/SoilWise-documentation/technical_components/storage/#git-user-enhanced-metadata
-  [x] Correction of ‘metadat’

https://soilwise-he.github.io/SoilWise-documentation/technical_components/metadata_authoring/
-  [x] In the box ‘info’, the URL links are not pointing to the corresponding adresses.

https://soilwise-he.github.io/SoilWise-documentation/infrastructure/containerization/
-  [x] Correction of « component, be it a database or other storage »

https://soilwise-he.github.io/SoilWise-documentation/infrastructure/git/
-  [x] When the ‘repository GIT’ is cited, is it better to talk about ‘repository GitHub’ (because it could be Gitlab or other software forges)

https://soilwise-he.github.io/SoilWise-documentation/technical_components/knowledge_graph/
-  [x] Correction of "knoledge"

https://soilwise-he.github.io/SoilWise-documentation/technical_components/user_management/
-  [x] After "As of now, there are three Identity providers deployed as part of that infrastructure:", modify the bullet points of the identity providers by another symbol like tick points for example.

**Comment by DajanaSnopkova** [comment]
Thanks for this thorough review. Checked boxes are resolved.

Merging the Table of contents... - I don't know exactly what do you mean here, but once the Terminology is clear, I plan to merge this to the glossary section.

Figure of architecture - unfortunately, I have not found a way how to display the figure directly on the architecture schema of SWR

Metadata augmentation - the chapter should be structured as it is. This means that only two functions are implemented now, and others are foreseen

Containerization - I am still not getting what needs to be fixed there. Sorry.

**Comment by blitzfrayret** [comment]
Hello Dajana and Nick, 

Thank you a lot for your responses and corrections inside the deliverable and the technical documentation. Concerning the issue on GitHub, I reply inside your text below (I start my comments by 'CBF'). 

Best wishes, 

Celine 


De: "Dajana Snopková" ***@***.***> 
À: "soilwise-he/SoilWise-documentation" ***@***.***> 
Cc: "Céline BLITZ-FRAYRET" ***@***.***>, "Author" ***@***.***> 
Envoyé: Lundi 23 Septembre 2024 08:47:34 
Objet: Re: [soilwise-he/SoilWise-documentation] Internal review D2.1 Technical documentation (Issue #54) 






Thanks for this thorough review. Checked boxes are resolved. 

Merging the Table of contents... - I don't know exactly what do you mean here, but once the Terminology is clear, I plan to merge this to the glossary section. 

CBF - The idea was indeed to have only one 'dictionary' instead of having on one side the glossary and on the other side the terminology. So it's ok to merge the terminology to the glossary section. 

Figure of architecture - unfortunately, I have not found a way how to display the figure directly on the architecture schema of SWR 

CBF - I understand, It was just a minor improvement I suggested ... 

Metadata augmentation - the chapter should be structured as it is. This means that only two functions are implemented now, and others are foreseen 

CBF - I thought I found the 'Metadata augmentation' as a subsection of another section with the wrong letters size, but I don't find it anymore, so you can delete this comment, sorry ! 

Containerization - I am still not getting what needs to be fixed there. Sorry. 

CBF - It is this sentence where I think some words are missing between "component," and "database" or maybe it should just be rephrased : "This means that each software component, be it a database or other storage, or a service of some kind, is compiled into a container image."

**Comment by DajanaSnopkova** [comment]
Thanks for the clarification.

For the Containerization, I rephrased this sentence: "This means that each software component, whether it's a database, storage system, or some kind of service, is compiled into a container image. "

**Comment by blitzfrayret** [comment]
Thank you Dajana, now everything is ok for me, have a good day, 

Celine 


De: "Dajana Snopková" ***@***.***> 
À: "soilwise-he" ***@***.***> 
Cc: "Céline BLITZ-FRAYRET" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mardi 24 Septembre 2024 07:57:23 
Objet: Re: [soilwise-he/SoilWise-documentation] Internal review D2.1 Technical documentation (Issue #54) 





Thanks for the clarification. 

For the Containerization, I rephrased this sentence: "This means that each software component, whether it's a database, storage system, or some kind of service, is compiled into a container image. "
